### PR TITLE
Playing with usability of Response<T>

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**
This PR includes the following changes:
1. Usability and informal API review improvements
    - deconstruction of Response<T>
    - better debugging support (overrides ToString and adds debugger view for SettingBatch)
    - name cleanup
    - removed default ctor from ConfigurationSetting
    - renamed namespace
    - added ConfigurationSetting.Equals
    - added indexer and Count to SettingBatch

2. Added license (this is a separate commit and you can skip it if you want to look at the other changes also)

Note: As I noted at some of the design reviews, I am not super happy with the usability of the Response\<T\> type. The type makes it very easy to be consistent in how status, headers, and deserialized payload are returned from service calls, but the main scenario of getting to the deserialized content  to not super elegant, i.e. the caller has to call response.Result property. This change is an idea to use C# deconstruction feature to make it much better IMO. I think this moves the type from "on the fence" to "I like it" in my book.

### CODE REVIEW

**Comment by johanste** [comment]
How is a paged operation exposed in this model? Today, most libraries will return an IEnumerable (in whatever construct your favorite language has) that will do paging transparently/internally.

**Comment by KrzysztofCwalina** [comment]
@johanste see https://github.com/Azure/azure-sdk-for-net-lab/blob/master/Configuration/Azure.Configuration.Test/ConfigurationMockTests.cs#L182

**Comment by johanste** [comment]
Ok - I would not have expected to have to unwrap/follow the next links manually in my application code (this is something that autorest generated code today will do for you under the hood).

I also have to take a look at what paging mechanism the service is using here, because it looks a bit odd (I would have expected either client driven paging or a transparent next link to be returned by the service - but it looks like there a is hybrid approach/an item count in the response per the code you linked to)

As a side note, The Microsoft REST API guidelines has some documentation on [how a service is expected to handle paging](https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#98-pagination).

**Comment by KrzysztofCwalina** [comment]
Yeah, I agree that having to manually following the links is not ideal. My thinking was that once C# adds support for IAsyncEnumerable<T> (in the works) we would provide a helper method. Right now there is really not a great solution. The original prototype library (developed by the configuration service team) used an unofficial IAsyncEnumerable that we cannot use as: a) it's 3rd party, b) will be obsoleted by the C# feature, c) does not integrate with C# foreach.

**Comment by JeffreyRichter** [comment]
For the record, I’m opposed to hiding the paging from the customer/developer.
First, some services (like Storage) charge real money for each operation and customers should know where in their code these costs are going to occur and they should explicitly accept these costs.
Second, code performance predictability: By writing 2 loops (the outer to get the page and the inner to process the page results), the customer knows that the inner loop incurs no costs and will be of high performance. The outer loop incurs costs and there is an I/O perf hit with each iteration. In fact, the customer should be able to pass a CancellationToken (or per-language equivalent) when doing the I/O operation.
Third, the kinds of failures that can occur from I/O are wildly different from the kinds of failures that can occur from the inner loop. If a failure happens in the inner loop, the customer can write code to get that 1 page again and process it. If you hide the fact that paging is occurring then the developer might write code that starts the paging from the beginning.
Fourth, memory management: If you hide the paging, then the customer is much more likely to enumerate all results and put them in a collection of some sort – this encourages them to wrote non-scalable code. The correct pattern is read a page, process a page and then repeat. Not read all pages and then process all results.

FYI: I worked with a MS team once that was using LINQ to process an enormous Azure Storage Table. Since LINQ hides the paging, the MS developer unknowingly wrote code that downloaded the entire Azure Table. This was a huge perf hit and incurs enormous costs. Testing of the code was done against a small table and so none of the problems existed. It wasn’t until the code was put into production that there was a big fire drill to fix the code and then the team expunged the use of LINQ form their code base.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Ftraining%2Fdistributed-cloud-apps%2F&data=02%7C01%7Cjeffreyr%40microsoft.com%7C948cf3366acf45f6ef8d08d62e3b3b00%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636747229263047172&sdata=sg%2FtzHWpscWQDr7foOSsaNrKDP5vNSHE3b72HJG8swU%3D&reserved=0>)

**Pull request merged**
